### ISSUE TITLE
Improvements in "Hat" section: "Export as CSV" (date as YYYY-MM-DD)

### ISSUE THREAD

**Issue by therob84** [larswolter/ultisite#37]
In the part ultisite/hat the CSV-Export of all data (db dump?!) is very helpful.
But it's usefulness is limited due to some problems I encountered this year:

1. make all dates ISO-conform, e.g. like YYYY-MM-DD hh:mm:ss.
Why? It should be the goal that Excel and LibreOffice can easily convert these dates into real date values/coloums during importing process of CSV file to allow sort/filtering.
Now it is something hardcoded like "Sun Oct 23 2022 19:50:25 GMT+0000 (Coordinated Universal Time)" which is quite hard to feed into excel/libre office without semi-manual separations.

2. make the order of entries of the CSV-file per default the same as it is displayed at the webpage, so that it can easily separated into the "playing list / waiting list / not yet payed or bestätigt". Other sortings can then be done manually (at least if point 1. is solved

Thanks Lars ;-)

**Comment by therob84** [comment]
Export is no in XLSX instead of CSV - fine.

One further thing: the values in the cols for "Strength, years, etc" should be numbers, but are exportet as text (with trailing apostroph ' ) - can this be changed to real numbers to do some math? 
Otherwise I would make it handish after export.
(funny: during test exactly ONE number is a real number, all other are text with a ' ...)
Thanks :-)

**Comment by larswolter** [comment]
fixed by commit 90a0023
